services:
    n8n_server:
        build:
            context: .
            dockerfile: n8n.Dockerfile
        restart: always
        environment:
            GENERIC_TIMEZONE: 'America/Sao_Paulo'
            TZ: 'America/Sao_Paulo'
            N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
            N8N_RUNNERS_ENABLED: true
            DB_TYPE: postgresdb
            DB_POSTGRESDB_DATABASE: n8n
            DB_POSTGRESDB_HOST: postgre
            DB_POSTGRESDB_PORT: 5432
            DB_POSTGRESDB_USER: postgres
            DB_POSTGRESDB_SCHEMA: public
            DB_POSTGRESDB_PASSWORD: root
        ports:
            - '5678:5678'
        volumes:
            - n8n_data:/home/node/.n8n
        depends_on:
            - postgre
        networks:
            - default

    postgre:
        build: 
            context: .
            dockerfile: postgresql.Dockerfile
        restart: always
        environment:
            POSTGRES_DB: n8n
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
        ports:
            - '5432:5432'
        volumes:
            - postgre_data:/var/lib/postgresql
        networks:
            - default

volumes:
    n8n_data:
    postgre_data:

networks:
    default:
        name: n8n_network

